# Generated by Django 5.0 on 2024-02-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeismicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("inv", models.JSONField()),
            ],
        ),
    ]
